# Generated by Django 4.1 on 2022-09-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(max_length=150, verbose_name='nome completo'),
        ),
    ]
